name: Build Tweak

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang git perl make libssl-dev curl

      - name: Setup Theos
        run: |
          # Cài đặt Theos chuẩn
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          
          # Đăng ký biến THEOS vào môi trường GitHub Actions
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build Package
        run: |
          $THEOS/bin/make package FINALPACKAGE=1

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dynamic-by-HDang-DEB
          path: packages/*.deb
