name: Build Tweak

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang git perl make libssl-dev unzip

      - name: Setup Theos and Build
        run: |
          # 1. Tải Theos
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          export THEOS=$HOME/theos
          
          # 2. Tải SDK iOS
          mkdir -p $THEOS/sdks
          curl -LO https://github.com/theos/sdks/archive/refs/heads/master.zip
          unzip -q master.zip
          mv sdks-master/* $THEOS/sdks/
          rm -rf sdks-master master.zip

          # 3. Tiến hành Build Package
          $THEOS/bin/make package FINALPACKAGE=1

      - name: Upload DEB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dynamic-by-HDang-DEB
          path: packages/*.deb
